apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ui
  namespace: default
spec:
  selector:
    matchLabels: 
      app: app-ui
  replicas: 1
  template:
    metadata:
      name: app-ui
      labels:
        app: app-ui
    spec:
      containers:
      - name: app-ui
        image: 881289302514.dkr.ecr.ap-south-1.amazonaws.com/app-ui # repository 
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: app-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: app-ui